//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WoblaExplorer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WoblaExplorer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B.
        /// </summary>
        internal static string Bytes {
            get {
                return ResourceManager.GetString("Bytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading application files.
        /// </summary>
        internal static string DeploymentProgressStateDownloadingApplicationFiles {
            get {
                return ResourceManager.GetString("DeploymentProgressStateDownloadingApplicationFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading application manifest.
        /// </summary>
        internal static string DeploymentProgressStateDownloadingApplicationInformation {
            get {
                return ResourceManager.GetString("DeploymentProgressStateDownloadingApplicationInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading deployment manifest.
        /// </summary>
        internal static string DeploymentProgressStateDownloadingDeploymentInformation {
            get {
                return ResourceManager.GetString("DeploymentProgressStateDownloadingDeploymentInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon ExplorerIcon {
            get {
                object obj = ResourceManager.GetObject("ExplorerIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ExplorerImage {
            get {
                object obj = ResourceManager.GetObject("ExplorerImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] FontAwesome {
            get {
                object obj = ResourceManager.GetObject("FontAwesome", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GB.
        /// </summary>
        internal static string GigaBytes {
            get {
                return ResourceManager.GetString("GigaBytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KB.
        /// </summary>
        internal static string KiloBytes {
            get {
                return ResourceManager.GetString("KiloBytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MB.
        /// </summary>
        internal static string MegaBytes {
            get {
                return ResourceManager.GetString("MegaBytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update completed.
        /// </summary>
        internal static string MwAppUpdatedHeader {
            get {
                return ResourceManager.GetString("MwAppUpdatedHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application has been updated you need to restart it..
        /// </summary>
        internal static string MwAppUpdatedText {
            get {
                return ResourceManager.GetString("MwAppUpdatedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose new place to item.
        /// </summary>
        internal static string MwCopyToDescription {
            get {
                return ResourceManager.GetString("MwCopyToDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t create a directory inside file!.
        /// </summary>
        internal static string MwCreateDirInFileError {
            get {
                return ResourceManager.GetString("MwCreateDirInFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new version of the application cannot be downloaded at this time. Please check your network connection, or try again later. Error: .
        /// </summary>
        internal static string MwDeploymentDownloadException {
            get {
                return ResourceManager.GetString("MwDeploymentDownloadException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot check for a new version of the application. The ClickOnce deployment is corrupt. Please redeploy the application and try again. Error: .
        /// </summary>
        internal static string MwInvalidDeploymentException {
            get {
                return ResourceManager.GetString("MwInvalidDeploymentException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This application cannot be updated. It is likely not a ClickOnce application. Error: .
        /// </summary>
        internal static string MwInvalidOperationException {
            get {
                return ResourceManager.GetString("MwInvalidOperationException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No updates found.
        /// </summary>
        internal static string MwNoUpdatesHeader {
            get {
                return ResourceManager.GetString("MwNoUpdatesHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your app have latest version..
        /// </summary>
        internal static string MwNoUpdatesText {
            get {
                return ResourceManager.GetString("MwNoUpdatesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this item(s)?.
        /// </summary>
        internal static string MwRemoveDialogText {
            get {
                return ResourceManager.GetString("MwRemoveDialogText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete file.
        /// </summary>
        internal static string MwRemoveDialogTitle {
            get {
                return ResourceManager.GetString("MwRemoveDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only one object at time can be renamed.
        /// </summary>
        internal static string MwRenameError {
            get {
                return ResourceManager.GetString("MwRenameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to completed in .
        /// </summary>
        internal static string MwSearchCompleted {
            get {
                return ResourceManager.GetString("MwSearchCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  now?.
        /// </summary>
        internal static string MwUpdateDialogContentAfterVersion {
            get {
                return ResourceManager.GetString("MwUpdateDialogContentAfterVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An update is available. Would you like to update the application to version .
        /// </summary>
        internal static string MwUpdateDialogContentBeforeVersion {
            get {
                return ResourceManager.GetString("MwUpdateDialogContentBeforeVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An update is available.
        /// </summary>
        internal static string MwUpdateDialogHeader {
            get {
                return ResourceManager.GetString("MwUpdateDialogHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This application cannot be updated. It is likely not a ClickOnce application..
        /// </summary>
        internal static string MwWrongAppUpdate {
            get {
                return ResourceManager.GetString("MwWrongAppUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking for updates....
        /// </summary>
        internal static string UdUpdateStageCheck {
            get {
                return ResourceManager.GetString("UdUpdateStageCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading updates....
        /// </summary>
        internal static string UdUpdateStageUpdating {
            get {
                return ResourceManager.GetString("UdUpdateStageUpdating", resourceCulture);
            }
        }
    }
}
